# Generated by Django 4.0.3 on 2024-10-23 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hesaplama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateTimeField()),
                ('bitis_tarihi', models.DateTimeField()),
                ('sonuc', models.CharField(max_length=10)),
                ('muhendis', models.CharField(max_length=100)),
                ('yapilan_is', models.CharField(max_length=255)),
                ('kule_adi', models.CharField(max_length=255)),
                ('kule_tipi', models.CharField(max_length=255)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
