# Generated by Django 4.0.3 on 2024-10-23 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hesaplama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaiKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateTimeField()),
                ('bitis_tarihi', models.DateTimeField()),
                ('muhendis', models.CharField(max_length=100)),
                ('yapilan_is', models.CharField(max_length=200)),
                ('kule_adi', models.CharField(max_length=100)),
                ('kule_tipi', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Hesaplama',
        ),
    ]
