# Generated by Django 4.0.3 on 2024-10-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0003_alter_mesaikaydi_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaikaydi',
            name='sonuc',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
