# Generated by Django 4.0.3 on 2024-10-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplama', '0004_mesaikaydi_sonuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaikaydi',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mesaikaydi',
            name='kule_adi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mesaikaydi',
            name='kule_tipi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mesaikaydi',
            name='muhendis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mesaikaydi',
            name='yapilan_is',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
